eureka:
  client:
    serviceUrl:
      defaultZone: http://liuhuan:haojiubujian@localhost:8761/eureka/
server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liu1sa/haojiubujian
          #searchPaths: spring-cloud/helloworldConfig
  application:
    name: order-server
  rabbitmq:
       host: localhost
       port: 5672
       username: guest
       password: guest
